2018-11-28 02:11:00.545 [main] ERROR com.yaya.o2o.service.impl.WeChatAuthServiceImpl -insertWechatAuth error:org.springframework.dao.DataIntegrityViolationException: 
### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'user_id' cannot be null
### The error may involve com.yaya.o2o.dao.WechatAuthDao.insertWechatAuth-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO tb_wechat_auth(         user_id,         open_id,         create_time)     VALUES(         ?,         ?,         ?     )
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'user_id' cannot be null
; SQL []; Column 'user_id' cannot be null; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'user_id' cannot be null
2018-11-28 09:58:59.040 [main] ERROR com.yaya.o2o.service.impl.WeChatAuthServiceImpl -insertWechatAuth error:org.springframework.dao.DataIntegrityViolationException: 
### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'user_id' cannot be null
### The error may involve com.yaya.o2o.dao.WechatAuthDao.insertWechatAuth-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO tb_wechat_auth(         user_id,         open_id,         create_time)     VALUES(         ?,         ?,         ?     )
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'user_id' cannot be null
; SQL []; Column 'user_id' cannot be null; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'user_id' cannot be null
2018-11-28 10:04:48.190 [main] ERROR com.yaya.o2o.service.impl.WeChatAuthServiceImpl -insertWechatAuth error:org.springframework.dao.DataIntegrityViolationException: 
### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'user_id' cannot be null
### The error may involve com.yaya.o2o.dao.WechatAuthDao.insertWechatAuth-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO tb_wechat_auth(         user_id,         open_id,         create_time)     VALUES(         ?,         ?,         ?     )
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'user_id' cannot be null
; SQL []; Column 'user_id' cannot be null; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'user_id' cannot be null
2018-11-28 10:42:01.122 [main] ERROR com.yaya.o2o.service.impl.WeChatAuthServiceImpl -insertWechatAuth error:org.springframework.dao.DuplicateKeyException: 
### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'testopenid' for key 'open_id'
### The error may involve com.yaya.o2o.dao.WechatAuthDao.insertWechatAuth-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO tb_wechat_auth(         user_id,         open_id,         create_time)     VALUES(         ?,         ?,         ?     )
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'testopenid' for key 'open_id'
; SQL []; Duplicate entry 'testopenid' for key 'open_id'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'testopenid' for key 'open_id'
2018-11-28 10:44:21.664 [main] ERROR com.yaya.o2o.service.impl.WeChatAuthServiceImpl -insertWechatAuth error:org.springframework.dao.DuplicateKeyException: 
### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'testopenid' for key 'open_id'
### The error may involve com.yaya.o2o.dao.WechatAuthDao.insertWechatAuth-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO tb_wechat_auth(         user_id,         open_id,         create_time)     VALUES(         ?,         ?,         ?     )
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'testopenid' for key 'open_id'
; SQL []; Duplicate entry 'testopenid' for key 'open_id'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'testopenid' for key 'open_id'
